import { useEffect, useState, type ReactNode } from 'react';
import { Link, useNavigate, useRouterState } from '@tanstack/react-router';
import { useTranslation } from 'react-i18next';
import { Bell, ChevronsLeft, ChevronsRight, LogOut, Menu, Search, ShieldCheck, X, WifiOff } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Avatar, AvatarFallback } from '@/components/ui/avatar';
import { Input } from '@/components/ui/input';
import { navigation } from './nav';
import { supabase } from '@/integrations/supabase/client';
import { setLanguage, languages, type Language } from '@/i18n';
import logo from '@/assets/aeronova-logo.png.asset.json';
import { useQueryClient } from '@tanstack/react-query';

export type Identity = { id:string; full_name:string; language:string; role:'admin'|'assistant' };
export function LanguageControl({ value, onChange }: { value: string; onChange:(value:Language)=>void }) { const {t}=useTranslation(); return <label className="inline-flex items-center gap-2 text-xs font-medium text-muted-foreground"><span className="sr-only">{t('language')}</span><select aria-label={t('language')} className="rounded-md border border-border bg-background px-2 py-1.5 text-foreground outline-none focus:ring-2 focus:ring-ring" value={value} onChange={e=>onChange(e.target.value as Language)}>{languages.map(lang=><option key={lang} value={lang}>{lang.toUpperCase()}</option>)}</select></label> }
export function Workspace({identity,children,title}: {identity:Identity;children:ReactNode;title:string}) {
 const {t}=useTranslation(); const navigate=useNavigate(); const queryClient=useQueryClient(); const pathname=useRouterState({select:s=>s.location.pathname});
 const [collapsed,setCollapsed]=useState(false); const [mobileOpen,setMobileOpen]=useState(false); const [online,setOnline]=useState(true);
 useEffect(()=>{ setOnline(navigator.onLine); const update=()=>setOnline(navigator.onLine); window.addEventListener('online',update);window.addEventListener('offline',update);return()=>{window.removeEventListener('online',update);window.removeEventListener('offline',update)} },[]);
 const items=navigation.filter(item=>!item.adminOnly||identity.role==='admin');
 const changeLanguage=async (language:Language)=>{setLanguage(language); await supabase.from('profiles').update({language}).eq('id',identity.id)};
 const signOut=async()=>{await queryClient.cancelQueries();queryClient.clear();await supabase.auth.signOut();navigate({to:'/auth',replace:true})};
 const navLink=(item:typeof navigation[number])=><Link key={item.key} to={item.path} onClick={()=>setMobileOpen(false)} title={t(item.key)} className={`group flex h-10 items-center gap-3 rounded-md px-3 text-sm font-medium transition-colors ${pathname===item.path?'bg-sidebar-accent text-sidebar-primary':'text-sidebar-foreground/65 hover:bg-sidebar-accent/60 hover:text-sidebar-foreground'} ${collapsed?'justify-center':''}`}><item.icon className="size-[18px] shrink-0" strokeWidth={1.8}/>{!collapsed&&<span className="truncate">{t(item.key)}</span>}</Link>;
 return <div className="min-h-screen bg-background text-foreground">
  {!online&&<div className="fixed inset-x-0 top-0 z-50 flex items-center justify-center gap-2 bg-foreground py-1.5 text-xs text-background"><WifiOff className="size-3"/>{t('offline')}</div>}
  <div className="flex min-h-screen">
   <aside className={`hidden shrink-0 flex-col border-e border-sidebar-border bg-sidebar transition-[width] duration-200 md:flex ${collapsed?'w-[72px]':'w-[250px]'}`}>
    <div className={`flex h-[76px] items-center border-b border-sidebar-border ${collapsed?'justify-center px-2':'justify-between px-5'}`}><Link to="/dashboard" className="flex min-w-0 items-center gap-3"><img src={logo.url} alt="Aeronova Engineering" className="size-10 shrink-0 rounded-md object-cover"/>{!collapsed&&<span className="min-w-0"><strong className="block truncate font-display text-base leading-5 text-sidebar-foreground">AERONOVA</strong><small className="block text-[9px] font-semibold tracking-[.22em] text-sidebar-foreground/45">ENGINEERING</small></span>}</Link></div>
    <nav className="flex-1 overflow-y-auto px-3 py-6" aria-label={t('menu')}>{['overview','fieldwork','management'].map(group=><div key={group} className="mb-6">{!collapsed&&<p className="mb-2 px-3 text-[10px] font-bold uppercase tracking-[.16em] text-sidebar-foreground/35">{t(group)}</p>}<div className="space-y-0.5">{items.filter(item=>item.group===group).map(navLink)}</div></div>)}</nav>
    <div className="border-t border-sidebar-border p-3"><div className={`mb-2 flex items-center gap-3 rounded-md px-2 py-2 ${collapsed?'justify-center':''}`}><Avatar className="size-9 shrink-0"><AvatarFallback className="bg-sidebar-accent text-sidebar-primary text-xs font-bold">{(identity.full_name||'A').slice(0,2).toUpperCase()}</AvatarFallback></Avatar>{!collapsed&&<div className="min-w-0"><p className="truncate text-sm font-semibold text-sidebar-foreground">{identity.full_name||'Aeronova'}</p><p className="text-xs text-sidebar-foreground/45">{t(identity.role)}</p></div>}</div><div className={`flex items-center ${collapsed?'flex-col':'justify-between'} gap-1`}><Button variant="ghost" size="icon" aria-label={t('signOut')} title={t('signOut')} onClick={signOut} className="text-sidebar-foreground/65"><LogOut/></Button>{!collapsed&&<LanguageControl value={identity.language} onChange={changeLanguage}/>}<Button variant="ghost" size="icon" onClick={()=>setCollapsed(!collapsed)} aria-label={t('menu')} title={t('menu')} className="text-sidebar-foreground/65">{collapsed?<ChevronsRight className="rtl:rotate-180"/>:<ChevronsLeft className="rtl:rotate-180"/>}</Button></div></div>
   </aside>
   <div className="flex min-w-0 flex-1 flex-col pb-[72px] md:pb-0">
    <header className="sticky top-0 z-20 flex h-[68px] items-center justify-between gap-3 border-b border-border bg-background/95 px-5 backdrop-blur-md md:h-[76px] md:px-8"><div className="flex min-w-0 items-center gap-3"><Button variant="ghost" size="icon" className="md:hidden" aria-label={t('menu')} onClick={()=>setMobileOpen(true)}><Menu/></Button><div className="min-w-0"><span className="block truncate text-xs text-muted-foreground">{t('workspace')} / {t(title)}</span><strong className="block truncate text-base font-semibold md:text-lg">{t(title)}</strong></div></div><div className="flex shrink-0 items-center gap-2"><Button variant="outline" className="hidden h-9 w-[230px] justify-start text-muted-foreground lg:flex" onClick={()=>navigate({to:'/search'})}><Search className="me-2 size-4"/>{t('searchPlaceholder')}</Button><Button variant="ghost" size="icon" aria-label={t('search')} className="lg:hidden" onClick={()=>navigate({to:'/search'})}><Search/></Button>{identity.role==='admin'&&<Button variant="ghost" size="icon" aria-label={t('notifications')} onClick={()=>navigate({to:'/notifications'})}><Bell/></Button>}<div className="ms-2 hidden md:block"><Avatar className="size-8"><AvatarFallback className="bg-accent text-accent-foreground text-xs">{(identity.full_name||'A').slice(0,2).toUpperCase()}</AvatarFallback></Avatar></div></div></header>
    <main className="mx-auto w-full max-w-[1440px] flex-1 px-5 py-7 md:px-8 md:py-9">{children}</main>
   </div>
  </div>
  <nav className="fixed inset-x-0 bottom-0 z-30 grid h-[72px] grid-cols-5 border-t border-border bg-background/98 pb-[env(safe-area-inset-bottom)] md:hidden" aria-label={t('menu')}>{['dashboard','calendar','visits','tasks'].map(key=>{const item=items.find(x=>x.key===key); if(!item)return null;return <Link key={key} to={item.path} className={`flex flex-col items-center justify-center gap-1 text-[10px] font-semibold ${pathname===item.path?'text-primary':'text-muted-foreground'}`}><item.icon className="size-5" strokeWidth={1.8}/>{t(key)}</Link>})}<Button variant="ghost" className="flex h-full flex-col gap-1 rounded-none text-[10px] text-muted-foreground" onClick={()=>setMobileOpen(true)}><Menu className="size-5"/>{t('menu')}</Button></nav>
  {mobileOpen&&<div className="fixed inset-0 z-40 md:hidden"><div className="absolute inset-0 bg-foreground/50" onClick={()=>setMobileOpen(false)}/><aside className="absolute inset-y-0 start-0 flex w-[min(320px,85vw)] flex-col bg-sidebar shadow-xl"><div className="flex items-center justify-between border-b border-sidebar-border p-5"><img src={logo.url} alt="Aeronova Engineering" className="h-11 w-auto rounded-md"/><Button variant="ghost" size="icon" aria-label={t('close')} onClick={()=>setMobileOpen(false)}><X/></Button></div><nav className="flex-1 overflow-auto px-3 py-4">{['overview','fieldwork','management'].map(group=><div key={group} className="mb-5"><p className="mb-2 px-3 text-[10px] font-bold uppercase tracking-widest text-muted-foreground">{t(group)}</p>{items.filter(item=>item.group===group&&!item.desktopOnly).map(navLink)}</div>)}</nav><div className="flex items-center justify-between border-t p-4"><LanguageControl value={identity.language} onChange={changeLanguage}/><Button variant="ghost" onClick={signOut}><LogOut/>{t('signOut')}</Button></div></aside></div>}
 </div>
}
