import { useState, type FormEvent } from 'react';
import { useNavigate } from '@tanstack/react-router';
import { useTranslation } from 'react-i18next';
import { ArrowRight, Eye, EyeOff, LockKeyhole, Mail, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { LanguageControl } from '@/features/shell/Workspace';
import { setLanguage, type Language } from '@/i18n';
import { supabase } from '@/integrations/supabase/client';
import logo from '@/assets/aeronova-logo.png.asset.json';
export function Login() {
 const {t,i18n}=useTranslation();const navigate=useNavigate();const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [showPassword,setShowPassword]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');const {data,error:authError}=await supabase.auth.signInWithPassword({email,password});if(authError||!data.user){setError(t('loginError'));setBusy(false);return}const {data:profile}=await supabase.from('profiles').select('id,is_active,language').eq('id',data.user.id).maybeSingle();const {data:role}=await supabase.from('user_roles').select('role').eq('user_id',data.user.id).maybeSingle();if(!profile?.is_active||!role){await supabase.auth.signOut();setError(t('accessDenied'));setBusy(false);return}setLanguage(profile.language as Language);navigate({to:'/dashboard',replace:true});setBusy(false)};
 return <div className="flex min-h-screen bg-background">
  <div className="relative hidden min-h-screen w-[52%] flex-col justify-between overflow-hidden bg-brand-panel px-14 py-12 text-brand-panel-foreground lg:flex"><div className="relative z-10"><img src={logo.url} alt="Aeronova Engineering" className="size-[76px] rounded-lg object-cover"/></div><div className="relative z-10 max-w-xl pb-8"><div className="mb-9 h-px w-14 bg-brand-gold"/><h1 className="font-display text-[clamp(2.5rem,4vw,4.5rem)] font-semibold leading-[1.12]">{t('brandLine')}</h1><p className="mt-6 max-w-md text-lg leading-relaxed text-brand-panel-muted">{t('brandDescription')}</p><div className="mt-16 flex items-center gap-3 text-xs font-semibold uppercase tracking-[.14em] text-brand-panel-muted"><ShieldCheck className="size-4 text-brand-gold"/>{t('privateAccess')}</div></div><span className="relative z-10 text-xs text-brand-panel-muted">{t('copyright')}</span><div className="pointer-events-none absolute -bottom-24 -end-32 size-[600px] rotate-45 border border-brand-panel-line"/><div className="pointer-events-none absolute -bottom-24 -end-32 size-[480px] rotate-45 border border-brand-panel-line"/><div className="pointer-events-none absolute -bottom-24 -end-32 size-[360px] rotate-45 border border-brand-panel-line"/></div>
  <div className="flex min-h-screen flex-1 flex-col px-6 py-6 sm:px-12 lg:px-16"><div className="flex items-center justify-between"><img src={logo.url} alt="Aeronova Engineering" className="size-12 rounded-md object-cover lg:hidden"/><span className="hidden text-xs font-semibold uppercase tracking-[.16em] text-muted-foreground lg:block">{t('workspace')}</span><LanguageControl value={i18n.language} onChange={setLanguage}/></div><div className="mx-auto flex w-full max-w-[420px] flex-1 flex-col justify-center py-16"><div className="mb-10"><div className="mb-7 flex size-12 items-center justify-center rounded-xl bg-accent text-primary"><LockKeyhole className="size-5"/></div><h2 className="font-display text-3xl font-semibold leading-tight text-foreground sm:text-4xl">{t('welcome')}</h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{t('loginSubtitle')}</p></div><form onSubmit={submit} className="space-y-5"><div><label htmlFor="email" className="mb-2 block text-sm font-medium">{t('email')}</label><div className="relative"><Mail className="pointer-events-none absolute start-4 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input id="email" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} className="h-12 ps-11 text-sm" placeholder="nom@aeronova.com"/></div></div><div><label htmlFor="password" className="mb-2 block text-sm font-medium">{t('password')}</label><div className="relative"><LockKeyhole className="pointer-events-none absolute start-4 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input id="password" type={showPassword?'text':'password'} autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)} className="h-12 ps-11 pe-12 text-sm"/><Button type="button" variant="ghost" size="icon" className="absolute end-1 top-1/2 -translate-y-1/2" aria-label={t(showPassword?'hidePassword':'showPassword')} onClick={()=>setShowPassword(!showPassword)}>{showPassword?<EyeOff/>:<Eye/>}</Button></div></div>{error&&<p role="alert" className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}<Button type="submit" disabled={busy} className="mt-2 h-12 w-full text-sm font-semibold">{busy?t('signingIn'):t('signIn')}<ArrowRight className="ms-auto size-4 rtl:rotate-180"/></Button></form><p className="mt-8 flex items-center justify-center gap-2 text-center text-xs text-muted-foreground"><ShieldCheck className="size-4"/>{t('accessHelp')}</p></div><div className="flex items-center justify-between border-t border-border pt-5 text-xs text-muted-foreground"><span>{t('copyright')}</span><span>{t('privateAccess')}</span></div></div>
 </div>
}
